export const AUTH = {
  AUTH:'auth/',
  LOGIN: "login",
  SIGNUP:'signup'
};

export const SITES ={
  SITES:'sites/',
  ADD_SITE:"add",
  SITES_LIST:"list",
  DELETE_SITE:"delete",
  RE_CRAWL_SITE:"re_crawl_site",
  SITE_LINKS_AND_CONTENT:"get_links",
  SITE_PAGE_INSIGHTS:"get_page_insights",
  SITE_CRAWLING_INFO:"site-crawling-info",
  SITE_RECOMMENDATION_DATA:"get-recommendations-data",
  SITE_RECOMMENDATION_COUNTS:"get-recommendations-count",
}

export const BILLING ={
  CHECKOUT:'/payment/request',
}

export const APIEndpoint = {
  BILLING:`${BILLING.CHECKOUT}`,
  LOGIN:`${AUTH.AUTH}${AUTH.LOGIN}`,
  SIGNUP:`${AUTH.AUTH}${AUTH.SIGNUP}`,
  ADD_SITE:`${SITES.SITES}${SITES.ADD_SITE}`,
  SITES_LIST:`${SITES.SITES}${SITES.SITES_LIST}`,
  DELETE_SITE:`${SITES.SITES}${SITES.DELETE_SITE}`,
  RE_CRAWL_SITE:`${SITES.SITES}${SITES.RE_CRAWL_SITE}`,
  SITE_PAGE_INSIGHTS:`${SITES.SITES}${SITES.SITE_PAGE_INSIGHTS}`,
  SITE_CRAWLING_INFO:`${SITES.SITES}${SITES.SITE_CRAWLING_INFO}`,
  SITE_LINKS_AND_CONTENT:`${SITES.SITES}${SITES.SITE_LINKS_AND_CONTENT}`,
  SITE_RECOMMENDATION_DATA:`${SITES.SITES}${SITES.SITE_RECOMMENDATION_DATA}`,
  SITE_RECOMMENDATION_COUNTS:`${SITES.SITES}${SITES.SITE_RECOMMENDATION_COUNTS}`,
}
