export const AUTH = {
  AUTH:'auth/',
  LOGIN: "login",
  SIGNUP:'signup',
  GOOGLE_AUTH:'social-auth'
};

export const SITES ={
  SITES:'sites/',
  ADD_SITE:"add_site",
  DELETE_SITE:"delete",
  SITES_LIST:"user_sites",
  GET_KEYWORDS:"get_keywords",
  RE_CRAWL_SITE:"re_crawl_site",
  SITE_CRAWLING_INFO:"get_site_data",
  SITE_LINKS_AND_CONTENT:"get_links",
  SITE_PAGE_INSIGHTS:"get_page_insights",
  GET_RECOMMENDATIONS_BY_TYPE:"data_by_type",
  UPDATE_RECOMMENDATION:"update-recommendation",
  APPROVE_RECOMMENDATIONS:"approve_recommendations",
}

export const BILLING ={
  STRIPE:'/stripe',
  USER_QUOTA:'/get-user-quota',
  CHECKOUT:'/create-subscription',
  BILLING_HISTORY:'/get-payment-history',
  STRIPE_PAYMENT_INTENT:'/create-payment-intent',
}

export const APIEndpoint = {
  CHECKOUT:`${BILLING.STRIPE}${BILLING.CHECKOUT}`,
  USER_QUOTA:`${BILLING.STRIPE}${BILLING.USER_QUOTA}`,
  BILLING_HISTORY:`${BILLING.STRIPE}${BILLING.BILLING_HISTORY}`,
  STRIPE_PAYMENT_INTENT:`${BILLING.STRIPE}${BILLING.STRIPE_PAYMENT_INTENT}`,

  LOGIN:`${AUTH.AUTH}${AUTH.LOGIN}`,
  SIGNUP:`${AUTH.AUTH}${AUTH.SIGNUP}`,
  GOOGLE_AUTH:`${AUTH.AUTH}${AUTH.GOOGLE_AUTH}`,
  
  ADD_SITE:`${SITES.SITES}${SITES.ADD_SITE}`,
  SITES_LIST:`${SITES.SITES}${SITES.SITES_LIST}`,
  DELETE_SITE:`${SITES.SITES}${SITES.DELETE_SITE}`,
  GET_KEYWORDS:`${SITES.SITES}${SITES.GET_KEYWORDS}`,
  RE_CRAWL_SITE:`${SITES.SITES}${SITES.RE_CRAWL_SITE}`,
  SITE_PAGE_INSIGHTS:`${SITES.SITES}${SITES.SITE_PAGE_INSIGHTS}`,
  SITE_CRAWLING_INFO:`${SITES.SITES}${SITES.SITE_CRAWLING_INFO}`,
  UPDATE_RECOMMENDATION:`${SITES.SITES}${SITES.UPDATE_RECOMMENDATION}`,
  SITE_LINKS_AND_CONTENT:`${SITES.SITES}${SITES.SITE_LINKS_AND_CONTENT}`,
  APPROVE_RECOMMENDATIONS:`${SITES.SITES}${SITES.APPROVE_RECOMMENDATIONS}`,
  GET_RECOMMENDATIONS_BY_TYPE:`${SITES.SITES}${SITES.GET_RECOMMENDATIONS_BY_TYPE}`,
}
