export const AUTH = {
  LOGIN: 'signin',
  SIGNUP: 'onboard',
  PROFILE_PAGE: 'user-profile',
  VERIFY_OTP: 'verify-top',
  UNAUTHORIZED: 'unauthorized',
  RESET_PASSWORD: 'reset-password',
  CHANGE_PASSWORD: 'update-password',
  FORGET_PASSWORD: 'forgot-password',
  PERMISSION_DENIED: 'permission-denied',
}

export const BILLING = {
  BASE: '/billing',
  PLANS: 'plans',
  CHECKOUT: 'checkout',
  BILLING_DETAIL: 'billing-detail',
  PAYMENT_HISTORY: 'payment-history',
  UPCOMING_INVOICES: 'upcoming-invoices',
}

export const SITES = {
  BASE: '/airanker/websites',
  ADD_SITE: 'add-website',
  SITES_PAGES: 'pages',
  SITES_LIST: 'all-websites',
  SITE_SCHEMA_PAGE: 'schema',
  SITE_SETTING_PAGE: 'setting',
  SITES_DASHBOARD: 'dashboard',
  SITE_INSIGHTS: 'website-insights',
  SITE_DETAILS_PAGE: 'website-detail',
  SCRIPT_SECTION: 'script-section',
  SITE_ACCESS_KEYS: 'access-tokens',
  RECOMMENDATIONS: 'recommendations',
  KEYWORDS_RANKING: 'keywords-ranking',
  ADD_SITES_NEW_KEYWORDS: 'add-new-keywords',
}

export const EXACT_ROUTES = {
  LOGIN: `/${AUTH.LOGIN}`,
  PROFILE_PAGE: `/${AUTH.PROFILE_PAGE}`,
  SIGNUP: `/${AUTH.SIGNUP}`,
  VERIFY_OTP: `/${AUTH.VERIFY_OTP}`,
  UNAUTHORIZED: `/${AUTH.UNAUTHORIZED}`,
  RESET_PASSWORD: `/${AUTH.RESET_PASSWORD}`,
  PERMISSION_DENIED: `/${AUTH.PERMISSION_DENIED}`,
  CHANGE_PASSWORD: `/${AUTH.CHANGE_PASSWORD}`,
  FORGET_PASSWORD: `/${AUTH.FORGET_PASSWORD}`,

  PLANS: `${BILLING.BASE}/${BILLING.PLANS}`,
  CHECKOUT: `${BILLING.BASE}/${BILLING.CHECKOUT}`,
  BILLING_DETAIL: `${BILLING.BASE}/${BILLING.BILLING_DETAIL}`,
  PAYMENT_HISTORY: `${BILLING.BASE}/${BILLING.PAYMENT_HISTORY}`,
  UPCOMING_INVOICES: `${BILLING.BASE}/${BILLING.UPCOMING_INVOICES}`,

  ADD_SITE: `${SITES.BASE}/${SITES.ADD_SITE}`,
  SITES_LIST: `${SITES.BASE}/${SITES.SITES_LIST}`,
  SITES_PAGES: `${SITES.BASE}/${SITES.SITES_PAGES}`,
  SITE_INSIGHTS: `${SITES.BASE}/${SITES.SITE_INSIGHTS}`,
  SCRIPT_SECTION: `${SITES.BASE}/${SITES.SCRIPT_SECTION}`,
  RECOMMENDATIONS: `${SITES.BASE}/${SITES.RECOMMENDATIONS}`,
  SITES_DASHBOARD: `${SITES.BASE}/${SITES.SITES_DASHBOARD}`,
  KEYWORDS_RANKING: `${SITES.BASE}/${SITES.KEYWORDS_RANKING}`,
  SITE_ACCESS_KEYS: `${SITES.BASE}/${SITES.SITE_ACCESS_KEYS}`,
  SITE_DETAILS_PAGE: `${SITES.BASE}/${SITES.SITE_DETAILS_PAGE}`,
  ADD_SITES_NEW_KEYWORDS: `${SITES.BASE}/${SITES.ADD_SITES_NEW_KEYWORDS}`,
}
